### ISSUE TITLE
tari_watcher: VN process and registration manager

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari-dan#1112]
## Problem

A validator node needs to be highly available both for the health of the network and to avoid losing out on fees.
Furthermore, a validator operator needs to manually monitor and re-register their node if their registration expires.

The following needs to be satisfied for a node to facilitate a highly available node:
- **Crash recovery** - process recover timeously if a crash is encountered
- **Registration management** - the validator should remain registered and should re-register if the registration expires
- **Notification and Visibility** - the node operator should be notified if the node crashes, or a registration has expired

There is currently no automated way to register and re-register a VN before expiry which has led to registrations expiring and stoppage of the network.

## Proposal

A new process manager called tari_watcher for validator node operators that monitors and restarts a validator node process, ensures the validator node is registered, automatically re-registers the validator node for the expiry epoch, and can be configured to submit status messages to supported channels.

#### Crash recovery

The tari_watcher forks a child VN process and restarts it if that process ends.

If the tari_watcher is terminated, the VN process should continue. optional: If/when the tari_watcher is restarted it should detect the active process and continue monitoring it (e.g pick up a PID file and monitor the process)

The user should be able to instruct tari_watcher to stop the VN process. 

#### Registration management

A user should be able to configure whether they would like to automatically register and re-register.

The tari_watcher will need to have a gRPC connection to a minotari node and minotari console wallet with the requisite gRPC methods enabled. The tari_watcher should also fetch consensus constants from the minotari node so that it is aware of the epoch length and registration validity period.

If `auto_register` is enabled, the tari_watcher should:
1. call [GetActiveValidatorNodes](https://github.com/tari-project/tari/blob/35573840c3b40f7e87b4021f8bed754be8e859cf/applications/minotari_app_grpc/proto/base_node.proto#L97) for any existing registrations for this node
2. if the validator node is not registered it should submit a registration 
3. poll [GetTipInfo](https://github.com/tari-project/tari/blob/35573840c3b40f7e87b4021f8bed754be8e859cf/applications/minotari_app_grpc/proto/base_node.proto#L77) and wait for the L1 chain to progress to the expiry epoch.
4. Once at the expiry epoch, submit a new registration. i.e. if the registration expires in epoch 200, and epoch length is 10 blocks, wait until the L1 tip height is 2000 and submit a registration transaction to the minotari console wallet using 
[RegisterValidatorNode](https://github.com/tari-project/tari/blob/35573840c3b40f7e87b4021f8bed754be8e859cf/applications/minotari_app_grpc/proto/wallet.proto#L82C7-L82C28).

#### Notification and visibility

The operator should be able to configure notifications optionally for one or more supported channels. The initial implementation should allow for future expansion.

The following events should be implemented:
- a node has crashed 
- a node registration has been submitted
- a node has restarted
- registration is close to expiring

Additional events could be added in future.

The following channels should be supported:
- mattermost
- telegram

Additional channels should be able to be added at a later point easily, and therefore their implementation should be abstracted from the core process and L1 monitoring.

#### Implementation

**Configuration** - should use a toml config format. The binary should be able to create an initial config file for later editing.
**Cli** - a clap cli interface should be used 
**Process management** - should be cross-platform. Tokio provides good async cross-platform child process management. Alternative suggestions are welcome 

Base layer scanning is already implemented and should be reused (however it is currently tightly coupled to validator node and indexer requirements)

The VN registration procedure is implemented in tari_swarm_daemon, so look there for code to use.

Configuration example: Feel free to change to whatever makes sense.

```toml
# If true, the watcher will automatically submit a validator node registration transaction initially and at expiration

auto_register = true | false
# The gRPC address for a minotari node
minotari_node_grpc_address = "my-host:12345"
# The gRPC address for the minotari console wallet
minotari_console_wallet_grpc_address = "my-host:12345" 
# The path of the validator node registration file. This file contains the signed information required to submit a registration transaction on behalf of the validator node
validator_node_registration_file = "~/.tari/validator_node/mainnet/registration.json"
# The sidechain ID to use. If not provided, the default Tari sidechain is implicitly used
sidechain_id = <none> | "deadbeaf123..."

# The channels to send event notifications
[channels]
mattermost = { enabled: true, credentials:{...} }
telegram = { enabled: true, credentials:{...} }

```
